# Generated by Django 3.2.7 on 2021-10-24 13:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='github_url',
            field=models.CharField(blank=True, max_length=300, null=True, validators=[django.core.validators.URLValidator], verbose_name='Github'),
        ),
    ]
