# Generated by Django 3.2.7 on 2021-09-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(max_length=2000, verbose_name='Description'),
        ),
    ]
