# Generated by Django 3.2.7 on 2021-09-17 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_issue_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='types',
            field=models.ManyToManyField(related_name='types', to='webapp.IssueType', verbose_name='Types'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='types_set', to='webapp.issuetype', verbose_name='Type_set'),
        ),
    ]
