# Generated by Django 3.2.7 on 2021-09-17 11:07

from django.db import migrations


def transfer_types(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.types.add(issue.type)


def rollback_transfer(apps, schema_editor):
    Issue = apps.get_model('webapp.Issue')
    for issue in Issue.objects.all():
        issue.type = issue.types.first()


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210917_1106'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
