# Generated by Django 3.2.7 on 2021-09-30 09:13

from django.db import migrations, models
import django.db.models.deletion
import webapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.ForeignKey(default='webapp.IssueStatus', on_delete=django.db.models.deletion.RESTRICT, related_name='statuses', to='webapp.issuestatus', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='summary',
            field=models.CharField(max_length=150, validators=[webapp.models.MinValueValidator(10)], verbose_name='Summary'),
        ),
    ]
