# Generated by Django 3.2.7 on 2021-10-06 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='project', to='webapp.project', verbose_name='Issue project'),
        ),
    ]
