# Generated by Django 3.2.7 on 2021-10-20 11:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0010_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='users',
            field=models.ManyToManyField(related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
