# Generated by Django 3.2.7 on 2021-10-20 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_issue_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='users',
        ),
    ]
